node_js:
  - 14

cache:
  yarn: true
  directories:
    - node_modules

env:
  global:
    - CI=test

services:
  - docker

before_install:
  docker pull node:14.10.1

before_script:
  - yarn install

script:
  - .auto-update/try.sh